runtime: go122
env: flex

env_variables:
  GIN_MODE: "release"
  DB_TYPE: "mysql"
  DB_HOST: "localhost"
  DB_PORT: "3306"
  DB_NAME: "gva"
  DB_USER: "root"
  DB_PASSWORD: ""
  JWT_SIGNING_KEY: "gin-vue-admin"
  ALIPAY_APP_ID: "2021000000000000"
  ALIPAY_SANDBOX_MODE: "true"

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10

resources:
  cpu: 1
  memory_gb: 1
  disk_size_gb: 10
