# github.com/flipped-aurora/gin-vue-admin/server Global Configuration

# jwt configuration
jwt:
  signing-key: qmPlus
  expires-time: 7d
  buffer-time: 1d
  issuer: qmPlus
# zap logger configuration
zap:
  level: info
  format: console
  prefix: "[github.com/flipped-aurora/gin-vue-admin/server]"
  director: log
  show-line: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true

# redis configuration
redis:
  db: 0
  addr: 177.7.0.14:6379
  password: ""

# mongo configuration
mongo:
  coll: ''
  options: ''
  database: ''
  username: ''
  password: ''
  min-pool-size: 0
  max-pool-size: 100
  socket-timeout-ms: 0
  connect-timeout-ms: 0
  is-zap: false
  hosts:
    - host: ''
      port: ''

# email configuration
email:
  to: xxx@qq.com
  port: 465
  from: xxx@163.com
  host: smtp.163.com
  is-ssl: true
  secret: xxx
  nickname: test

# system configuration
system:
  env: public  # Change to "develop" to skip authentication for development mode
  addr: 8888
  db-type: mysql
  oss-type: local    # 控制oss选择走本地还是 七牛等其他仓 自行增加其他oss仓可以在 server/utils/upload/upload.go 中 NewOss函数配置
  use-redis: false     # 使用redis
  use-mongo: false     # 使用mongo
  use-multipoint: false
  # IP限制次数 一个小时15000次
  iplimit-count: 15000
  #  IP限制一个小时
  iplimit-time: 3600

# captcha configuration
captcha:
  key-long: 6
  img-width: 240
  img-height: 80
  open-captcha: 0 # 0代表一直开启，大于0代表限制次数
  open-captcha-timeout: 3600 # open-captcha大于0时才生效

# mysql connect configuration
# 未初始化之前请勿手动修改数据库信息！！！如果一定要手动初始化请看（https://gin-vue-admin.com/docs/first_master）
mysql:
  path: ""
  port: ""
  config: ""
  db-name: ""
  username: ""
  password: ""
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: ""
  log-zap: false

# pgsql connect configuration
# 未初始化之前请勿手动修改数据库信息！！！如果一定要手动初始化请看（https://gin-vue-admin.com/docs/first_master）
pgsql:
  path: ""
  port: ""
  config: ""
  db-name: ""
  username: ""
  password: ""
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: ""
  log-zap: false

db-list:
  - disable: true # 是否禁用
    type: "" # 数据库的类型,目前支持mysql、pgsql
    alias-name: "" # 数据库的名称,注意: alias-name 需要在db-list中唯一
    path: ""
    port: ""
    config: ""
    db-name: ""
    username: ""
    password: ""
    max-idle-conns: 10
    max-open-conns: 100
    log-mode: ""
    log-zap: false


# local configuration
local:
  path: uploads/file
  store-path: uploads/file

# autocode configuration
autocode:
  transfer-restart: true
  # root 自动适配项目根目录
  # 请不要手动配置,他会在项目加载的时候识别出根路径
  root: ""
  server: /server
  server-plug: /plugin/%s
  server-api: /api/v1/%s
  server-initialize: /initialize
  server-model: /model/%s
  server-request: /model/%s/request/
  server-router: /router/%s
  server-service: /service/%s
  web: /web/src
  web-api: /api
  web-form: /view
  web-table: /view

# qiniu configuration (请自行七牛申请对应的 公钥 私钥 bucket 和 域名地址)
qiniu:
  zone: ZoneHuaDong
  bucket: ""
  img-path: ""
  use-https: false
  access-key: ""
  secret-key: ""
  use-cdn-domains: false

# aliyun oss configuration
aliyun-oss:
  endpoint: yourEndpoint
  access-key-id: yourAccessKeyId
  access-key-secret: yourAccessKeySecret
  bucket-name: yourBucketName
  bucket-url: yourBucketUrl
  base-path: yourBasePath

# alipay configuration
alipay:
  app_id: "2021000122674017"
  private_key: "MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCY7c+qT8E1+UVD+S6VnYEqgd7BzCQcCZqE4KR5SqDGV3WLgL+JgSEjVZOhHupqGJqkVa/TcUv8vQyvHrh+50RAVVtFHZkBZHwXS9mlGA2f7Qqg6mB7ZqxA7/Pf4CZEZJLyBxXQqXH5EwZOe5D4MxqNJH4R4KBW6i6YvZqK0tgNXGbKkB4UMJ5wcZRhQZLb0ZqYUPUNcqAZHB3GZoSqEUxiVb3BxqGaEGPcZrMGvwbPJfJ7R4PGxrVBOVLvI4v8AyXwZgz3qV4dHgQzjXPf+yvzxQBgxS9k8nYqm7b8Vw3mCwwGhGHq4RLlAN0rZxF4p+qxH8I5ufyQWo5Yw7JbAgMBAAECggEABZN5HaIVkS4ruXGm0YBXvQXPD9YzWYEj0ZQGIJBgHX9MBxBVCJHYqnZkLi1F+RxLRYfHzjQJPmDhUvFYQeZ0QxPJtPqDZbhBzuXE5QgwuAHBuJBQQEDIg5PSKxZ8Q4DR4JjbvtVE4oHRY0Y5qBwjr1VIQvmDZvh+Qj4hAVQIDAQABAoIBAQCY7c+qT8E1+UVD+S6VnYEqgd7BzCQcCZqE4KR5SqDGV3WLgL+JgSEjVZOhHupqGJqkVa/TcUv8vQyvHrh+50RAVVtFHZkBZHwXS9mlGA2f7Qqg6mB7ZqxA7/Pf4CZEZJLyBxXQqXH5EwZOe5D4MxqNJH4R4KBW6i6YvZqK0tgNXGbKkB4UMJ5wcZRhQZLb0ZqYUPUNcqAZHB3GZoSqEUxiVb3BxqGaEGPcZrMGvwbPJfJ7R4PGxrVBOVLvI4v8AyXwZgz3qV4dHgQzjXPf+yvzxQBgxS9k8nYqm7b8Vw3mCwwGhGHq4RLlAN0rZxF4p+qxH8I5ufyQWo5Yw7JbAgMBAAECggEABZN5HaIVkS4ruXGm0YBXvQXPD9YzWYEj0ZQGIJBgHX9MBxBVCJHYqnZkLi1F+RxLRYfHzjQJPmDhUvFYQeZ0QxPJtPqDZbhBzuXE5QgwuAHBuJBQQEDIg5PSKxZ8Q4DR4JjbvtVE4oHRY0Y5qBwjr1VIQvmDZvh+Qj4hAVQIDAQAB"
  public_key: "MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAmO3Pqk/BNflFQ/kulZ2BKoHewcwkHAmahOCkeUqgxld1i4C/iYEhI1WToR7qahiapFWv03FL/L0Mrx64fudEQFVbRR2ZAWR8F0vZpRgNn+0KoOpge2asQO/z3+AmRGSS8gcV0Klx+RMGTnuQ+DMajSR+EeCgVuoumL2aitLYDVxmypAeFDCecHGUYUGS29GamFD1DXKgGRwdxmaEqhFMYlW9wcahmhBj3GazBr8GzyXye0eDxsa1QTlS7yOL/AMl8GYM96leHR4EM41z3/sr88UAYMUvZPJ2Kpu2/FcN5gsMBoRh6uES5QDdK2cReKfqsR/CObj8kFqOWMOyWwIDAQAB"
  notify_url: "https://backend-web-app-ca74ufzk.fly.dev/api/v1/payment/notify"
  return_url: "https://frontend-web-app-ca74ufzk.devinapps.com/payment/success"
  sandbox_mode: true

# tencent cos configuration
tencent-cos:
  bucket: xxxxx-10005608
  region: ap-shanghai
  secret-id: your-secret-id
  secret-key: your-secret-key
  base-url: https://gin.vue.admin
  path-prefix: github.com/flipped-aurora/gin-vue-admin/server

# aws s3 configuration (minio compatible)
aws-s3:
  bucket: xxxxx-10005608
  region: ap-shanghai
  endpoint: ""
  s3-force-path-style: false
  disable-ssl: false
  secret-id: your-secret-id
  secret-key: your-secret-key
  base-url: https://gin.vue.admin
  path-prefix: github.com/flipped-aurora/gin-vue-admin/server

# huawei obs configuration
hua-wei-obs:
  path: you-path
  bucket: you-bucket
  endpoint: you-endpoint
  access-key: you-access-key
  secret-key: you-secret-key

# excel configuration
excel:
  dir: ./resource/excel/

# timer task db clear table
Timer:
  start: true
  spec: "@daily"  # 定时任务详细配置参考 https://pkg.go.dev/github.com/robfig/cron/v3
  detail:
    - tableName: sys_operation_records
      compareField: created_at
      interval: 2160h
    - tableName: jwt_blacklists
      compareField: created_at
      interval: 168h

# 跨域配置
# 需要配合 server/initialize/router.go -> `Router.Use(middleware.CorsByRules())` 使用
cors:
  mode: whitelist
  whitelist:
    - allow-origin: frontend-web-app-ca74ufzk.devinapps.com
      allow-headers: content-type,authorization
      allow-methods: GET, POST, PUT, DELETE, OPTIONS
      expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type, Authorization
      allow-credentials: true
