app = "backend-web-app-ca74ufzk"
primary_region = "sin"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8000"
  GIN_PORT = "8888"
  GIN_MODE = "release"

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services]]
  internal_port = 8888
  protocol = "tcp"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
