[project]
name = "gin-vue-admin-server"
version = "1.0.0"
description = "Gin Vue Admin Server"
requires-python = ">=3.8"

[build-system]
requires = ["setuptools>=42"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["app"]
